# Generated by Django 5.2.4 on 2025-08-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestSchools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cabinet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyBestSchools.cabinet'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=None, to='MyBestSchools.subject'),
        ),
    ]
